---
version: feature-test-templ
slug: dnsmasq-dhcp
name: Dnsmasq-DHCP
description: A simple DHCP server based on dnsmasq
url: https://github.com/f18m/ha-addon-dnsmasq-dhcp-server/tree/main
advanced: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
host_network: true
image: ghcr.io/f18m/{arch}-addon-dnsmasq-dhcp
init: false
ingress: true
ingress_stream: true
options:
  default_lease: 12h
  dns:
    - 8.8.8.8
    - 8.8.4.4
  hosts: 
    - mac: aa:bb:cc:dd:ee:ff
      name: an-important-host-with-static-ip
      ip: 192.168.1.15
  network:
    broadcast: 192.168.1.255
    gateway: 192.168.1.254
    interface: enp1s0
    netmask: 255.255.255.0
    range_end: 192.168.1.250
    range_start: 192.168.1.50
    subnet: 192.168.1.0
schema:
  default_lease: str
  dns:
    - str
  hosts:
    - ip: str
      mac: str
      name: str
  network:
    broadcast: str
    gateway: str
    interface: str
    netmask: str
    range_end: str
    range_start: str
    subnet: str
startup: system
privileged:
  - NET_ADMIN
