---
version: 0.0.1
slug: dnsmasq-dhcp
name: Dnsmasq-DHCP
description: A simple DHCP server based on dnsmasq
url: https://github.com/f18m/ha-addon-dnsmasq-dhcp-server/tree/main
advanced: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
host_network: true
#image: homeassistant/{arch}-addon-dnsmasq
init: false
options:
  defaults:
    - 8.8.8.8
    - 8.8.4.4
schema:
  defaults:
    - str
startup: system
