name: "Test Addon Build"

on: [push, pull_request]

jobs:

#   publish-docker:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Build and push Docker image
#         uses: mr-smithers-excellent/docker-build-push@v6
#         with:
#           # options related to BUILDing the docker image:
#           dockerfile: ./Dockerfile
#           multiPlatform: true
#           platform: linux/amd64,linux/arm64,linux/arm/v7
#           image: dnsmasq-dhcp-server
#           addLatest: true
#           # options related to PUSHing the docker image:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.PAT_TOKEN_FOR_GITHUB }}

  test-build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          path: ./myaddon
      - name: Test build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --all \
            --target myaddon \
            --branch main
