name: "Publish"

on: 
  push:
    branches:
      - '**'
    tags:
      - '*'


jobs:
  publish-docker-image:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          path: ./myaddon

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # build & push for MAIN branch
      - name: Docker build and push (main branch)
        uses: home-assistant/builder@master
        with:
          args: |
            --amd64 \
            --target myaddon \
            --docker-hub ghcr.io/f18m
        if: ${{ github.ref == 'refs/heads/main' }}

      # build & push for FEATURE branches
      # notice the additional --version and --no-latest flags:
      # get a good docker tag, which can be used to differentiate the 
      - name: Metadata extraction
        id: meta
        uses: docker/metadata-action@v5
        if: ${{ github.ref != 'refs/heads/main' }}

      - run: |
          echo "Docker image will be versioned as: ${{ steps.meta.outputs.version }}"
        if: ${{ github.ref != 'refs/heads/main' }}

      - name: Docker build and push (non-main branch)
        uses: home-assistant/builder@master
        with:
          args: |
            --amd64 \
            --target myaddon \
            --docker-hub ghcr.io/f18m \
            --version ${{ steps.meta.outputs.version }} \
            --no-latest
        if: ${{ github.ref != 'refs/heads/main' }}
