name: "Publish"

on: 
  push:
    branches:
      - '**'
    tags:
      - '*'


jobs:
  check_tag:
    name: Check if Tag Build
    runs-on: ubuntu-latest
    outputs:
      is_tag: ${{ steps.check.outputs.is_tag }}

    steps:
    - name: Check if it's a tagged release
      id: check
      run: |
        echo "GITHUB_REF is: ${GITHUB_REF}"
        if [[ -n "${GITHUB_REF##*refs/tags/*}" ]]; then
          echo "This looks like a non-TAG build"
          echo "is_tag=false" >> $GITHUB_ENV
          echo "is_tag=false" >> $GITHUB_OUTPUT
        else
          echo "This looks like a TAG build"
          echo "is_tag=true" >> $GITHUB_ENV
          echo "is_tag=true" >> $GITHUB_OUTPUT
        fi
    - run: |
        echo "This is a TAG build"
      if: ${{ steps.check.outputs.is_tag }}
    - run: |
        echo "This is a non-TAG build"
      if: ${{ ! steps.check.outputs.is_tag }}

  publish-docker-image:
    name: Publish
    runs-on: ubuntu-latest
    needs: check_tag
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          path: ./myaddon

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # build & push for TAG builds
      - name: Docker build and push (tags)
        uses: home-assistant/builder@master
        with:
          args: |
            --amd64 \
            --target myaddon \
            --docker-hub ghcr.io/f18m
        if: ${{ needs.check_tag.outputs.is_tag }}

      # build & push for non-TAG builds
      - name: Metadata extraction
        id: meta
        uses: docker/metadata-action@v5
        if: ${{ ! needs.check_tag.outputs.is_tag }}

      - run: |
          echo "Docker image will be versioned as: ${{ steps.meta.outputs.version }}"
        if: ${{ ! needs.check_tag.outputs.is_tag }}

      # notice the additional --version and --no-latest flags
      # compared to the variant for TAG builds:
      - name: Docker build and push (non-tag builds)
        uses: home-assistant/builder@master
        with:
          args: |
            --amd64 \
            --target myaddon \
            --docker-hub ghcr.io/f18m \
            --version ${{ steps.meta.outputs.version }} \
            --no-latest
        if: ${{ ! needs.check_tag.outputs.is_tag }}
