name: "Publish"

#on:
#  release:
#    types: [published]
#on: [push, pull_request]
on: push


jobs:
  publish-docker-image:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          path: ./myaddon
      - name: Extract Branch Name
        shell: bash
        run: |
          branchName=${GITHUB_REF#refs/heads/}
          if [ $branchName = 'develop' ]; then additionalImageName='-develop'; else additionalImageName=''; fi
          echo "additionalImageName=$(echo $additionalImageName)" >>$GITHUB_OUTPUT
        id: extract_branch
      - name: Get Branch
        run: |
          cd ./myaddon
          branch=$(git branch -r --contains ${{ github.ref }} --format "%(refname:lstrip=3)")
          echo "branchName=$(echo $branch)" >>$GITHUB_OUTPUT
        id: extract_branch2
      - run: |
          echo foo ${{ steps.extract_branch.outputs.additionalImageName }}
          echo bar ${{ steps.extract_branch2.outputs.branchName }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target myaddon \
            --docker-hub ghcr.io/f18m 
