name: "Publish"

#on:
#  release:
#    types: [published]
#on: [push, pull_request]
on: push


jobs:
  publish-docker-image:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          path: ./myaddon
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
      - run: |
          echo tags: ${{ steps.meta.outputs.tags }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --amd64 \
            --target myaddon \
            --docker-hub ghcr.io/f18m \
            --version ${{ steps.meta.outputs.tags }}
