name: "Tests"

on: 
  push:
    branches:
      - '**'
    tags:
      - '*'


jobs:
  unit-tests:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Build golang code
        run: |
          cd dhcp-clients-webapp-backend
          go build -o uibackend main.go

      - name: Run unit tests
        run: |
          cd dhcp-clients-webapp-backend
          go test -v -cover ./...
